<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>system_university</AssemblyName>
    <RootNamespace>system_university</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CA1416;CS8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Windows.Forms" />
    <Using Include="System.Data" />
    <Using Include="System.Data.SqlClient" />
    <Using Include="System.Drawing" />
  </ItemGroup>

</Project>